version: '3.7'

services:
    web-laratwitter:
        container_name: web-laratwitter
        image: nginx:1.17
        build:
            context: .
            dockerfile: infra/docker/web/Dockerfile
        ports:
            - "8888:80"
        volumes:
            - ./infra/docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - ./php-fpm-run:/var/run/php
            - ./:/var/www/laravel # ホスト側のパスを指定したパスにマウントする
        depends_on:
            - app-laratwitter
        links:
            - app-laratwitter

    app-laratwitter:
        container_name: app-laratwitter
        image: work/app-laratwitter:latest # ローカルにあるタグ名やimageId ローカルになければリモートへ取りに行く
        build:
            context: .
            dockerfile: infra/docker/app/Dockerfile # 構築に使うDockerfileの場所を指定
        tty: true # コンテナを起動させ続けられる
        volumes:
            - ./:/var/www/laravel # ホスト側のパスを指定したパスにマウントする
        # ports:
            # - "8000:8000"
        environment:    # 環境変数を指定
            TZ: "Asia/Tokyo"
            LANG: "ja_JP.UTF-8"
            LC_ALL: "ja_JP.UTF-8"
        # depends_on:
        #     db-laratwitter

    db-laratwitter:
        image: work/db-laratwitter
        container_name: db-laratwitter
        build:
            context: .
            dockerfile: infra/docker/db/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
            LANG: "ja_JP.UTF-8"
            LC_ALL: "ja_JP.UTF-8"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="STRICT_TRANS_TABLES"
        volumes:
            - ./infra/docker/db/persistence:/var/lib/mysql
            - ./infra/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./infra/docker/db/sql:/docker-entrypoint-initdb.d
